arm: right
controlled_joints:
- odom_x_joint
- odom_y_joint
- odom_z_joint
- triangle_base_joint
- left_arm_0_joint
- left_arm_1_joint
- left_arm_2_joint
- left_arm_3_joint
- left_arm_4_joint
- left_arm_5_joint
- left_arm_6_joint
- right_arm_0_joint
- right_arm_1_joint
- right_arm_2_joint
- right_arm_3_joint
- right_arm_4_joint
- right_arm_5_joint
- right_arm_6_joint
goal_pose_name: knorr_tomate_gp3
projection_mode: false
sim_frequency: 100
simulated_joints:
- odom_x_joint
- odom_y_joint
- odom_z_joint
- left_arm_0_joint
- left_arm_1_joint
- left_arm_2_joint
- left_arm_3_joint
- left_arm_4_joint
- left_arm_5_joint
- left_arm_6_joint
- right_arm_0_joint
- right_arm_1_joint
- right_arm_2_joint
- right_arm_3_joint
- right_arm_4_joint
- right_arm_5_joint
- right_arm_6_joint
- triangle_base_joint
- neck_shoulder_pan_joint
- neck_shoulder_lift_joint
- neck_elbow_joint
- neck_wrist_1_joint
- neck_wrist_2_joint
- neck_wrist_3_joint
- left_gripper_joint
- right_gripper_joint
simulated_links:
- base_link
- triangle_base_link
- triangle_right_arm_link
- calib_right_arm_base_link
- right_arm_1_link
- right_arm_2_link
- right_arm_3_link
- right_arm_4_link
- right_arm_5_link
- right_arm_6_link
- right_arm_7_link
- right_arm_flange_link
- right_arm_cabling_adaptor_link
- right_arm_adapter_iso50_kms40_frame_in
- right_arm_adapter_iso50_kms40_frame_out
- right_arm_kms40_frame_in
- right_arm_kms40_frame_out
- right_arm_adapter_kms40_fwk050_frame_in
- right_arm_adapter_kms40_fwk050_frame_out
- right_arm_fwk_fwa_050_frame_in
- right_arm_fwk_fwa_050_frame_out
- right_arm_adapter_fwa050_wsg50_frame_in
- right_arm_adapter_fwa050_wsg50_frame_out
- right_gripper_base_link
- right_gripper_tool_frame
start_config:
  left_arm_0_joint: -1.0424206770318125
  left_arm_1_joint: 0.7856426143571664
  left_arm_2_joint: -0.6005778452870986
  left_arm_3_joint: -1.664941382894658
  left_arm_4_joint: -1.9399642647890991
  left_arm_5_joint: -1.6535906309055022
  left_arm_6_joint: -2.572054542448777
  neck_shoulder_lift_joint: -3.0928
  neck_shoulder_pan_joint: -1.67144
  neck_wrist_1_joint: 1.23036
  neck_wrist_2_joint: 1.54493
  neck_wrist_3_joint: 0.04506
  odom_x_joint: -1.8
  odom_y_joint: -0.2
  odom_z_joint: -0.07
  right_arm_0_joint: 0.9318561286348706
  right_arm_1_joint: -0.617115289630847
  right_arm_2_joint: -2.5853490151650087
  right_arm_3_joint: -1.5708929937611393
  right_arm_4_joint: -1.3310840639433288
  right_arm_5_joint: 1.7323502336223708
  right_arm_6_joint: -0.9896413787705906
  triangle_base_joint: -0.31
watchdog_period: 0.1
