arm: left
controlled_joints:
- odom_x_joint
- odom_y_joint
- odom_z_joint
- triangle_base_joint
- left_arm_0_joint
- left_arm_1_joint
- left_arm_2_joint
- left_arm_3_joint
- left_arm_4_joint
- left_arm_5_joint
- left_arm_6_joint
- right_arm_0_joint
- right_arm_1_joint
- right_arm_2_joint
- right_arm_3_joint
- right_arm_4_joint
- right_arm_5_joint
- right_arm_6_joint
goal_pose_name: cup_gp3
projection_mode: false
sim_frequency: 100
simulated_joints:
- odom_x_joint
- odom_y_joint
- odom_z_joint
- left_arm_0_joint
- left_arm_1_joint
- left_arm_2_joint
- left_arm_3_joint
- left_arm_4_joint
- left_arm_5_joint
- left_arm_6_joint
- right_arm_0_joint
- right_arm_1_joint
- right_arm_2_joint
- right_arm_3_joint
- right_arm_4_joint
- right_arm_5_joint
- right_arm_6_joint
- triangle_base_joint
- neck_shoulder_pan_joint
- neck_shoulder_lift_joint
- neck_elbow_joint
- neck_wrist_1_joint
- neck_wrist_2_joint
- neck_wrist_3_joint
- left_gripper_joint
- right_gripper_joint
simulated_links:
- base_link
- triangle_base_link
- triangle_left_arm_link
- calib_left_arm_base_link
- left_arm_1_link
- left_arm_2_link
- left_arm_3_link
- left_arm_4_link
- left_arm_5_link
- left_arm_6_link
- left_arm_7_link
- left_arm_flange_link
- left_arm_cabling_adaptor_link
- left_arm_adapter_iso50_kms40_frame_in
- left_arm_adapter_iso50_kms40_frame_out
- left_arm_kms40_frame_in
- left_arm_kms40_frame_out
- left_arm_adapter_kms40_fwk050_frame_in
- left_arm_adapter_kms40_fwk050_frame_out
- left_arm_fwk_fwa_050_frame_in
- left_arm_fwk_fwa_050_frame_out
- left_arm_adapter_fwa050_wsg50_frame_in
- left_arm_adapter_fwa050_wsg50_frame_out
- left_gripper_base_link
- left_gripper_tool_frame
start_config:
  left_arm_0_joint: -1.7854974269866943
  left_arm_1_joint: 1.05581533908844
  left_arm_2_joint: 0.7688883543014526
  left_arm_3_joint: -1.867079496383667
  left_arm_4_joint: -2.5957729816436768
  left_arm_5_joint: -0.8040546178817749
  left_arm_6_joint: -2.445258855819702
  odom_x_joint: 0.2785887702017164
  odom_y_joint: -0.4578390367317157
  odom_z_joint: -0.0009559578255160022
  right_arm_0_joint: -0.5409327745437622
  right_arm_1_joint: 0.5533322691917419
  right_arm_2_joint: -1.2477020025253296
  right_arm_3_joint: -0.6026984453201294
  right_arm_4_joint: -0.2773824632167816
  right_arm_5_joint: 0.2725813090801239
  right_arm_6_joint: 1.092894434928894
  triangle_base_joint: -0.2077976
watchdog_period: 0.1
