arm: left
controlled_joints:
- odom_x_joint
- odom_y_joint
- odom_z_joint
- triangle_base_joint
- left_arm_0_joint
- left_arm_1_joint
- left_arm_2_joint
- left_arm_3_joint
- left_arm_4_joint
- left_arm_5_joint
- left_arm_6_joint
- right_arm_0_joint
- right_arm_1_joint
- right_arm_2_joint
- right_arm_3_joint
- right_arm_4_joint
- right_arm_5_joint
- right_arm_6_joint
goal_pose_name: knorr_tomate_gp1
projection_mode: false
sim_frequency: 100
simulated_joints:
- odom_x_joint
- odom_y_joint
- odom_z_joint
- left_arm_0_joint
- left_arm_1_joint
- left_arm_2_joint
- left_arm_3_joint
- left_arm_4_joint
- left_arm_5_joint
- left_arm_6_joint
- right_arm_0_joint
- right_arm_1_joint
- right_arm_2_joint
- right_arm_3_joint
- right_arm_4_joint
- right_arm_5_joint
- right_arm_6_joint
- triangle_base_joint
- neck_shoulder_pan_joint
- neck_shoulder_lift_joint
- neck_elbow_joint
- neck_wrist_1_joint
- neck_wrist_2_joint
- neck_wrist_3_joint
- left_gripper_joint
- right_gripper_joint
simulated_links:
- base_link
- triangle_base_link
- triangle_left_arm_link
- calib_left_arm_base_link
- left_arm_1_link
- left_arm_2_link
- left_arm_3_link
- left_arm_4_link
- left_arm_5_link
- left_arm_6_link
- left_arm_7_link
- left_arm_flange_link
- left_arm_cabling_adaptor_link
- left_arm_adapter_iso50_kms40_frame_in
- left_arm_adapter_iso50_kms40_frame_out
- left_arm_kms40_frame_in
- left_arm_kms40_frame_out
- left_arm_adapter_kms40_fwk050_frame_in
- left_arm_adapter_kms40_fwk050_frame_out
- left_arm_fwk_fwa_050_frame_in
- left_arm_fwk_fwa_050_frame_out
- left_arm_adapter_fwa050_wsg50_frame_in
- left_arm_adapter_fwa050_wsg50_frame_out
- left_gripper_base_link
- left_gripper_tool_frame
start_config:
  left_arm_0_joint: -0.9615
  left_arm_1_joint: 0.8983
  left_arm_2_joint: -0.6097
  left_arm_3_joint: -1.5235
  left_arm_4_joint: -1.837
  left_arm_5_joint: -1.6221
  left_arm_6_joint: -2.48
  neck_shoulder_lift_joint: -3.0928
  neck_shoulder_pan_joint: -1.67144
  neck_wrist_1_joint: 1.23036
  neck_wrist_2_joint: 1.54493
  neck_wrist_3_joint: 0.04506
  odom_x_joint: -1.5
  odom_y_joint: 0.5
  odom_z_joint: -0.07
  right_arm_0_joint: 0.955
  right_arm_1_joint: -0.591
  right_arm_2_joint: -2.509
  right_arm_3_joint: -1.457
  right_arm_4_joint: -1.234
  right_arm_5_joint: 1.804
  right_arm_6_joint: -1.068
  triangle_base_joint: -0.31
watchdog_period: 0.1
